# Chapter 1: Introduction to PyTorch

## What is PyTorch?
#### 1) A numpy replacement, because you can use GPUs.
#### 2) Really good framework for deep learning, easy to pick up and flexible.


## Installation
#### Refer to https://pytorch.org/get-started/locally/



In [11]:
# This is to test the correct installation of pytorch and demonstrate tensor declarations, operations, and mutation.
from __future__ import print_function
import torch

x = torch.rand(5,3) # fill it with random elements
x = torch.empty(5,3) # unintiallized elements
x = torch.tensor([5, 4, 3, 2]) # create directly
x = torch.zeros(5,3,dtype=torch.long) # fill it with zeros

y = torch.randn_like(x, dtype=torch.float) # Use other tensor's value, override the datatype, and have a tensor of similar size

# Addition operation
print(x+y) # add two tensors
print(torch.add(x,y)) # another way to add two tensors

# Save the results in another tensor
z = torch.empty(5, 3)
torch.add(x, y, out = z)
print(z)

y.add_(x) # add x to y
print(y)

print(x[:, 1]) # indexing

# Resizing tensors
x1 = torch.rand(4,4)
x2 = x1.view(16, 1)
x3 = x1.view(-1,8)




tensor([[-1.2127,  0.5996,  0.1455],
        [ 2.1565,  0.0317, -3.3597],
        [ 1.0156,  1.5986, -0.4302],
        [ 0.4523, -0.0621,  0.4127],
        [-0.4205, -0.5773, -0.9087]])
tensor([[-1.2127,  0.5996,  0.1455],
        [ 2.1565,  0.0317, -3.3597],
        [ 1.0156,  1.5986, -0.4302],
        [ 0.4523, -0.0621,  0.4127],
        [-0.4205, -0.5773, -0.9087]])
tensor([[-1.2127,  0.5996,  0.1455],
        [ 2.1565,  0.0317, -3.3597],
        [ 1.0156,  1.5986, -0.4302],
        [ 0.4523, -0.0621,  0.4127],
        [-0.4205, -0.5773, -0.9087]])
tensor([[-1.2127,  0.5996,  0.1455],
        [ 2.1565,  0.0317, -3.3597],
        [ 1.0156,  1.5986, -0.4302],
        [ 0.4523, -0.0621,  0.4127],
        [-0.4205, -0.5773, -0.9087]])
tensor([0, 0, 0, 0, 0])


In [14]:
# Converting to numpy
a = torch.tensor([1, 2, 4])
b = a.numpy()
print(a, b)
a.add_(1) # Changing the tensor would change its numpy equivalent
print(a, b)

tensor([1, 2, 4]) [1 2 4]
tensor([2, 3, 5]) [2 3 5]


In [16]:
# Converting from numpy
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)
np.add(a, 1, out=a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
# Move tensors to cuda
if torch.cuda.is_available():
    device = torch.device("cuda")          
    y = torch.ones_like(x, device=device) 
    x = x.to(device)            
    z = x + y
    print(z)
    print(z.to("cpu", torch.double)) 